[target.x86_64-unknown-linux-musl]
image = "ci/cross:x86_64-unknown-linux-musl"

[target.i686-unknown-linux-gnu]
image = "ci/cross:i686-unknown-linux-gnu"

[target.mips64-unknown-linux-gnuabi64]
image = "ci/cross:mips64-unknown-linux-gnuabi64"

[target.arm-unknown-linux-gnueabihf]
image = "ci/cross:arm-unknown-linux-gnueabihf"
